training_pipeline_config:
  pipeline_name: climate
  artifact_dir: artifact

data_ingestion_config:
  dataset_download_url: https://raw.githubusercontent.com/Ashishkumar-hub/Climate-Visiblity/main/Training_Batch_Files/visibility_08012014_120016.csv
  raw_data_dir: raw_data
  ingested_dir: ingested_data
  ingested_train_dir: train
  ingested_test_dir: test 