model_selection:
  module_0:
    class: LinearRegression
    module: sklearn.linear_model
    params:
      fit_intercept: true
    search_param_grid:
      fit_intercept:
      - true
      - false

  module_1:
    class: RandomForestRegressor
    module: sklearn.ensemble
    params:
      min_samples_leaf: 3
      max_depth: 2
    search_param_grid:
      min_samples_leaf:
      - 6 
      - 2
      - 3
      max_depth:
      - 9
      - 10
      - 11
      - 12
      - 15


  module_2:
    class: DecisionTreeRegressor
    module: sklearn.tree
    params:
      min_samples_leaf: 3
      max_depth: 2
    search_param_grid:
      min_samples_leaf:
      - 6 
      - 2
      - 3
      max_depth:
      - 8
      - 9
      - 10
      - 11
      - 12

  module_3:
    class: Ridge
    module: sklearn.linear_model
    params:
      alpha: 1
      fit_intercept: true
    search_param_grid:
      fit_intercept:
      - true
      - false
      alpha:
      - 1
      - 2
  
  module_4:
    class: Lasso
    module: sklearn.linear_model
    params:
      alpha: 1
      fit_intercept: true
    search_param_grid:
      fit_intercept:
      - true
      - false
      alpha:
      - 1
      - 2