columns:
  DATE: object
  VISIBILITY: float64
  DRYBULBTEMPF: int64
  WETBULBTEMPF: int64
  DewPointTempF: int64
  RelativeHumidity: int64 
  WindSpeed: int64
  WindDirection: int64
  StationPressure: float64
  SeaLevelPressure: float64
  Precip: float64

numerical_columns:
  - VISIBILITY
  - DRYBULBTEMPF
  - WETBULBTEMPF
  - DewPointTempF
  - RelativeHumidity
  - WindSpeed
  - WindDirection
  - StationPressure
  - SeaLevelPressure
  - Precip

categorical_columns:
  - DATE

target_column:
  - VISIBILITY